steps:
  - name: gcr.io/cloud-builders/yarn
    args:
      - install
    id: Install required packages
  - name: gcr.io/cloud-builders/yarn
    args:
      - '-c'
      - >
        echo "$$YARNRC" > /root/.yarnrc.yml

        chmod 400 /root/.yarnrc.yml

        yarn publish --access public
    id: Publish package
    entrypoint: bash
    secretEnv:
      - YARNRC
availableSecrets:
  secretManager:
    - versionName: projects/455829342814/secrets/yarnrc-yml-npm-hypcode-th/versions/latest
      env: YARNRC
