steps:
  - name: bash
    args:
      - '-c'
      - >
        echo "//registry.npmjs.org/:_authToken=$$NPM_ACCESS_TOKEN" >> /root/.npmrc

        echo "@hypcode-th:registry=https://registry.npmjs.org/" >> /root/.npmrc

        chmod 400 /root/.npmrc

    id: Prepare .npmrc
    secretEnv:
      - NPM_ACCESS_TOKEN
    volumes:
      - name: home
        path: /root/
  - name: 'gcr.io/cloud-builders/npm'
    args:
      - install
    id: Install required packages
  - name: 'gcr.io/cloud-builders/npm'
    args:
      - run
      - build
    id: Build package
  - name: 'gcr.io/cloud-builders/npm'
    args:
      - publish
      - --access
      - public
    id: Publish npm package
    env:
      - HOME=/root/
    volumes:
      - name: home
        path: /root/
availableSecrets:
  secretManager:
    - versionName: projects/455829342814/secrets/npm-granular-access-token-hypcode-th/versions/latest
      env: NPM_ACCESS_TOKEN
