steps:
  - name: bash
    args:
      - '-c'
      - >
        echo "$$NPMRC" > /root/.npmrc

        chmod 400 /root/.npmrc

    id: Prepare .npmrc
    secretEnv:
      - NPMRC
    volumes:
      - name: npmrc
        path: /root/.npmrc
  - name: gcr.io/cloud-builders/node
    args:
      - install
    entrypoint: npm
    id: Install required packages
  - name: gcr.io/cloud-builders/node
    args:
      - run
      - build
    entrypoint: npm
    id: Build package
  - name: gcr.io/cloud-builders/node
    args:
      - publish
      - --access
      - public
    entrypoint: npm
    id: Publish npm package
    volumes:
      - name: npmrc
        path: /root/.npmrc
availableSecrets:
  secretManager:
    - versionName: projects/455829342814/secrets/npmrc-hypcode-th/versions/latest
      env: NPMRC
