steps:
  - name: bash
    args:
      - '-c'
      - >
        echo "$$NPMRC" > /root/.npmrc

        chmod 400 /root/.npmrc

    id: Prepare .npmrc
    secretEnv:
      - NPMRC
    volumes:
      - name: home
        path: /root/
  - name: 'gcr.io/cloud-builders/npm'
    args:
      - install
    id: Install required packages
  - name: 'gcr.io/cloud-builders/npm'
    args:
      - run
      - build
    id: Build package
  - name: 'gcr.io/cloud-builders/npm'
    args:
      - publish
      - --access
      - public
    id: Publish npm package
    env:
      - HOME=/root/
    volumes:
      - name: home
        path: /root/
availableSecrets:
  secretManager:
    - versionName: projects/455829342814/secrets/npmrc-hypcode-th/versions/latest
      env: NPMRC
